# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: cd4ce439a24dd78d448d14fa7063683550438816966d41179063cef103eb9467220a3f93ab7d104c72fa86748d4ce36a35507e22d562bce5586a122a03bd6e9e

test:
  secret_key_base: d3f6fe1a7f50c8efbdb28f500dc1a852eb409731bd87d551809f536d7007f344030b03c9144c98cb68721cdd39e378d1b0fee16a4fc004b11a90df095818a337

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
